What does Pandas stand for?
<!-- A: python data analysis -->
What are the 2 collections used in Pandas?
<!-- A: DataFrames and Series -->
Name 4 things Pandas can do for us.
<!-- A: Data cleansing, Data normalization, Data Visualization, Data inspection   -->
To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
What is a CSV
<!-- A: a comma separated file -->
When cleaning data what values do we not like in our data?
<!-- A: duplicates, null values -->

In [1]:
import numpy as np
a1 = np.array([2, 3, 2])
print("a1 ...\n", a1)

a1 ...
 [2 3 2]


In [14]:
import numpy as np
array = np.linspace(0, 20,  num=6)
print(array)
new_array = np.copy(array)
# print(new_array)
array1 = new_array.__deepcopy__(array)
print(array1) 



[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]


In [15]:
# Using NumPy, 'broadcast' the multiplication of the following 2 arrays below to a 2-D array using the newaxis parameter ...
from numpy import array, newaxis
# create variables to store the array
a = array ([0.71, 0.1, 0.24, 0.3])
b = array([0.8, 0.59, 1.0, 1.11])
print(a * b)

[0.568 0.059 0.24  0.333]


In [23]:
# Concatenate these 3 arrays into a new array named 'newArray'...
import numpy as np
# create 3 different variable to store arrays
a_1 = np.array([[25 ,16]])
a_2 = np.array([[11, 2], [13, 4]])
a_3 = np.array([[7, 81], [5,6], [11, 12]])
# concatenate the 3 variables
arraycombo = np.concatenate((a_1, a_2, a_3))
print(arraycombo)
# Sort 'newArray' in order into 'sortedArray'
sortedArray = np.sort(arraycombo)
print("\nsortedArry...\n", sortedArray)
# Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.
reshapedArray = np.reshape(sortedArray, (2,2,3))
print("\nreshapedArray...\n", reshapedArray)
# Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.
a, b = c, d = reshapedArray
print("a = ", a)
print("b = ", b)
print("c = ", c)
print("d = ", d)

 


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

sortedArry...
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]

reshapedArray...
 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]
a =  [[16 25  2]
 [11  4 13]]
b =  [[ 7 81  5]
 [ 6 11 12]]
c =  [[16 25  2]
 [11  4 13]]
d =  [[ 7 81  5]
 [ 6 11 12]]


In [37]:
# Combined and sort the following arrays into one called 'comboArray' ...

import numpy as np
# create 3 variables to store arrays in
one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([0, 1, 2, 3, 4, 5, 6, 7])
# concatenate arrays
comboArray2 = np.concatenate((one, two, three))
print(comboArray2)
comboArray = np.sort(comboArray2)
print("\ncomboArray ...\n", comboArray)
# print sec1 - the 2nd element
print(comboArray[1])
# print sec2 - all elements from the 3rd element to the last
print(comboArray[2:26])
# print sec3 - all elements from the 4th to the 14th elements
print(comboArray[3:15])
# print sec4 - the last 6 elements
print(comboArray[18:26])
# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print(comboArray[-24:-10])
# print sec6 - from #20 every even element to the end
print(comboArray[16:25:2])
# print sec7 - from the last element moving forward, every 5th element.
print(comboArray[-1:1:-5])

[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]

comboArray ...
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15 16]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [47]:
# Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in pont #7.
import numpy as np   
arr1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

arr2 = np.array([[17.0, 70.0, 10.7]])
arr3 = np.subtract(arr1, arr2)
print(arr3)

[[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]


In [68]:
# Using Series, create a DataFrame that looks like this:
import pandas as pd
# create variables for each column
ingredients = pd.Series(["----", "flour", "milk", "eggs", "spam"], name= 'ingredients')
quantity = pd.Series(["----", 4, 1, 2, 1], name= 'quantity')
unit = pd.Series(["----", "cups", "cup", "large", "can"], name= 'unit')

# concatenate 3 series into dataframe
df = pd.concat([ingredients, quantity, unit], axis=1)
print(df)

                         


  ingredients quantity   unit
0        ----     ----   ----
1       flour        4   cups
2        milk        1    cup
3        eggs        2  large
4        spam        1    can


In [66]:
# Take this data and create a DataFrame named studentData
import pandas as pd

data = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }
# convert dictionary into dataframe
df = pd.DataFrame(data)
print(df)
# Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
df.insert(4, "deserts", ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"],True)
print("question 22", df)
df.sort_values(by= ['Name', 'address'], inplace = True)
print("question 23", df)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
question 22       Name  Height Qualification  address       deserts  Age        Pets   
0      Jai     5.1           Msc    Delhi     ice cream   21         Dog  \
1  janusha     6.2            MA     Doha  Cashew Fudge   23       Bunny   
2   Gaurav     5.1           Msc  Chennai       waffels   24  Chinchilla   
3     Anuj     5.2           Msc   Dakhar  Carrot Halwa   21      Parrot   

            sport  
0           Darts  
1      Basketball  
2  PaddleBoarding  
3         Cricket  
question 23       Name  Height Qualification  address       deserts  Age        Pets   
3     Anuj     5.2           Msc   Dakhar  C

In [67]:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv("cow_and_goats.csv")

In [71]:
# (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.
veg = pd.Series(["carrots", "celery", "spinach"], name= "vegetables")
veg_fact = pd.Series(["orange", "green", "dark green"], name= "color")
# concat both series into a dataframe
df = pd.concat([veg,veg_fact], axis=1)
print(df)
df.to_csv("Rodneyvege.csv")
# (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.
newveg = pd.read_csv("Rodneyvege.csv")
newveg.sort_values(by=["vegetables"], inplace=True)
newveg.to_csv("Rodneynewveg.csv")


  vegetables       color
0    carrots      orange
1     celery       green
2    spinach  dark green
